### ISSUE TITLE
Global refactor of the reportingExecutionByTag

### ISSUE THREAD

**Issue by afnogueira** [vertigo17/Cerberus#560]
This issue goal is to perform the refactoring of the page: "Reporting Execution By Tag" in order to improve its usage.

**List of requirements**
- [x] Issue  #536 - Execution Report By Tag : Organization of test cases
- [x] Issue  #547 - Improve "Execution Report By Tag" report
- [x] Issue  #553 - ReportingExecutionByTag is not sorted
- [x] Issue #554 - Reporting by tag : add sort per test case status
- [x] Export data into excel format and/or CSV files
- [x] Refactoring of the charts’ areas. 
- [x] Implementation of search mechanisms: by tag, system, country and environment. Get a list of the suitable fields.
- [x] Filter option: show results for test cases that are active in QA or/and UAT.  (related to #554)
- [x] In addition to the number of KO, Ok… it be useful to show its corresponding percentage value.
- [x]  In the execution report by tag Differentiate between the numerical statistics applications Mainsites / Mobile / Apps
- [x] Cannot view execution report for tests that do not require a browser to run #573
- [x] ReportingExecutionByTag.jsp : Chrome : Not able to click #580
- [x] Add Summary of the total and percentages values for each result code

**Comment by afnogueira** [comment]
Item "Show the number of attempts performed till get the final result." was removed from the list of requirements. This will be addressed in another issue.

**Comment by bcivel** [comment]
Done by @corentindms
